#!/bin/sh
APPDIR=../..;
if [ "$GWT_HOME" == "" ]; then
	echo "The environment variable GWT_HOME is not defined, it should point to a valid GWT installation."
	exit
fi

# Defaults for pre GWT 2.0
START_ON_FIRST_THREAD="-XstartOnFirstThread"
MAIN=HostedMode

if [ -f $GWT_HOME/gwt-dev.jar ] ; then
  START_ON_FIRST_THREAD=""
  MAIN=DevMode
fi

java -Xmx256m $START_ON_FIRST_THREAD -cp "$APPDIR/src:$APPDIR/war/WEB-INF/classes:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-mac.jar:$GWT_HOME/gwt-dev.jar:../../../../gwt-ajaxloader.jar" com.google.gwt.dev.${MAIN} -war "$APPDIR/war" "$@" -startupUrl HelloAjaxLoader.html com.google.gwt.ajaxloader.sample.helloajaxloader.HelloAjaxLoader;
