#!/bin/sh
APPDIR=../..;
if [ "$GWT_HOME" == "" ]; then
	echo "The environment variable GWT_HOME is not defined, it should point to a valid GWT installation."
	exit
fi

java -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar:../../../../gwt.search.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.google.gwt.search.sample.search.AJAXSearch;
