#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar:../../gwt-google-apis.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.google.gwt.gears.sample.managedresourcestore.ManagedResourceStoreDemo;