/*
 * Copyright 2008 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.gwt.opensocial.client.util;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.opensocial.client.MediaItem;

/**
 * A class encapsulating the parameters taken by an activity request, as created
 * by
 * {@link com.google.gwt.opensocial.client.DataRequest#newFetchActivitiesRequest(com.google.gwt.opensocial.client.DataRequest.Id, Map)}.
 */
public class ActivityParams extends JavaScriptObject {
  protected ActivityParams() {
  }
  
  /**
   * @return A string specifying the application that this activity is
   *         associated with.
   */
  public final native String getAppId() /*-{
    return this[$wnd.opensocial.Activity.Field.APP_ID];
  }-*/;

  /**
   * @return A string specifying an optional expanded version of an activity.
   */
  public final native String getBody() /*-{
    return this[$wnd.opensocial.Activity.Field.BODY];
  }-*/;

  /**
   * @return A string specifying the body template message ID in the gadget
   *         spec.
   */
  public final native String getBodyId() /*-{
    return this[$wnd.opensocial.Activity.Field.BODY_ID];
  }-*/;

  /**
   * @return An optional string ID generated by the posting application.
   */
  public final native String getExternalId() /*-{
    return this[$wnd.opensocial.Activity.Field.EXTERNAL_ID];
  }-*/;

  /**
   * @return A string ID that is permanently associated with this activity.
   */
  public final native String getId() /*-{
    return this[$wnd.opensocial.Activity.Field.ID];
  }-*/;

  /**
   * @return Any photos, videos, or images that should be associated with the
   *         activity.
   */
  public final native Array<MediaItem> getMediaItems() /*-{
    return this[$wnd.opensocial.Activity.Field.MEDIA_ITEMS];
  }-*/;

  /**
   * @return A string specifying the time at which this activity took place in
   *         milliseconds since the epoch.
   */
  public final native String getPostedTime() /*-{
    return this[$wnd.opensocial.Activity.Field.POSTED_TIME];
  }-*/;

  /**
   * @return A number between 0 and 1 representing the relative priority of this
   *         activity in relation to other activities from the same source
   */
  public final native float getPriority() /*-{
    return this[$wnd.opensocial.Activity.Field.PRIORITY];
  }-*/;

  /**
   * @return A string specifying the URL for the stream's favicon.
   */
  public final native String getStreamFavIconIUrl() /*-{
    return this[$wnd.opensocial.Activity.Field.STREAM_FAVICON_URL];
  }-*/;

  /**
   * @return A string specifying the stream's source URL.
   */
  public final native String getStreamSourceUrl() /*-{
    return this[$wnd.opensocial.Activity.Field.STREAM_SOURCE_URL];
  }-*/;

  /**
   * @return A string specifing the title of the stream.
   */
  public final native String getStreamTitle() /*-{
    return this[$wnd.opensocial.Activity.Field.STREAM_TITLE];
  }-*/;

  /**
   * @return A string specifying the stream's URL.
   */
  public final native String getStreamUrl() /*-{
    return this[$wnd.opensocial.Activity.Field.STREAM_URL];
  }-*/;

  /**
   * @return A map of custom keys to values associated with this activity.
   */
  public final native Map<String, Object> getTemplateParams() /*-{
    return this[$wnd.opensocial.Activity.Field.TEMPLATE_PARAMS];
  }-*/;

  /**
   * @return A string specifying the primary text of an activity.
   */
  public final native String getTitle() /*-{
    return this[$wnd.opensocial.Activity.Field.TITLE];
  }-*/;

  /**
   * @return A string specifying the title template message ID in the gadget
   *         spec.
   */
  public final native String getTitleId() /*-{
    return this[$wnd.opensocial.Activity.Field.TITLE_ID];
  }-*/;

  /**
   * @return A string specifying the URL that represents this activity.
   */
  public final native String getUrl() /*-{
    return this[$wnd.opensocial.Activity.Field.URL];
  }-*/;

  /**
   * @return The string ID of the user who this activity is for.
   */
  public final native String getUserId() /*-{
    return this[$wnd.opensocial.Activity.Field.USER_ID];
  }-*/;

  /**
   *
   * @param appId A string specifying the application that this activity is
   *        associated with.
   */
  public final native void setAppId(String appId) /*-{
    this[$wnd.opensocial.Activity.Field.APP_ID] = appId;
  }-*/;

  /**
   *
   * @param body A string specifying an optional expanded version of an
   *        activity.
   */
  public final native void setBody(String body) /*-{
    this[$wnd.opensocial.Activity.Field.BODY] = body;
  }-*/;

  /**
   *
   * @param bodyId A string specifying the body template message ID in the
   *        gadget spec.
   */
  public final native void setBodyId(String bodyId) /*-{
    this[$wnd.opensocial.Activity.Field.BODY_ID] = bodyId;
  }-*/;

  /**
   *
   * @param externalId An optional string ID generated by the posting
   *        application.
   */
  public final native void setExternalId(String externalId) /*-{
    this[$wnd.opensocial.Activity.Field.EXTERNAL_ID] = externalId;
  }-*/;

  /**
   * @param id A string ID that is permanently associated with this activity.
   */
  public final native void setId(String id) /*-{
    this[$wnd.opensocial.Activity.Field.ID] = id;
  }-*/;

  /**
   *
   * @param mediaItems Any photos, videos, or images that should be associated
   *        with the activity.
   */
  public final native void setMediaItems(Array<MediaItem> mediaItems) /*-{
    this[$wnd.opensocial.Activity.Field.MEDIA_ITEMS] = mediaItems;
  }-*/;

  /**
   *
   * @param postedTime A string specifying the time at which this activity took
   *        place in milliseconds since the epoch.
   */
  public final native void setPostedTime(String postedTime) /*-{
    this[$wnd.opensocial.Activity.Field.POSTED_TIME] = postedTime;
  }-*/;

  /**
   *
   * @param priority A number between 0 and 1 representing the relative priority
   *        of this activity in relation to other activities from the same
   *        source
   */
  public final native void setPriority(float priority) /*-{
    this[$wnd.opensocial.Activity.Field.PRIORITY] = priority;
  }-*/;

  /**
   *
   * @param streamFavIconUrl A string specifying the URL for the stream's
   *        favicon.
   */
  public final native void setStreamFavIconUrl(String streamFavIconUrl) /*-{
    this[$wnd.opensocial.Activity.Field.STREAM_FAVICON_URL] = streamFavIconUrl;
  }-*/;

  /**
   *
   * @param streamSourceUrl A string specifying the stream's source URL.
   */
  public final native void setStreamSourceUrl(String streamSourceUrl) /*-{
    this[$wnd.opensocial.Activity.Field.STREAM_SOURCE_URL] = streamSourceUrl;
  }-*/;

  /**
   *
   * @param streamTitle A string specifing the title of the stream.
   */
  public final native void setStreamTitle(String streamTitle) /*-{
    this[$wnd.opensocial.Activity.Field.STREAM_TITLE] = streamTitle;
  }-*/;

  /**
   *
   * @param streamUrl A string specifying the stream's URL.
   */
  public final native void setStreamUrl(String streamUrl) /*-{
    this[$wnd.opensocial.Activity.Field.STREAM_URL] = streamUrl;
  }-*/;

  /**
   *
   * @param templateParams A map of custom keys to values associated with this
   *        activity.
   */
  public final native void setTemplateParams(Map<String, Object> templateParams) /*-{
    this[$wnd.opensocial.Activity.Field.TEMPLATE_PARAMS] = templateParams;
  }-*/;

  /**
   *
   * @param title A string specifying the primary text of an activity.
   */
  public final native void setTitle(String title) /*-{
    this[$wnd.opensocial.Activity.Field.TITLE] = title;
  }-*/;

  /**
   *
   * @param titleId A string specifying the title template message ID in the
   *        gadget spec.
   */
  public final native void setTitleId(String titleId) /*-{
    this[$wnd.opensocial.Activity.Field.TITLE_ID] = titleId;
  }-*/;

  /**
   *
   * @param url A string specifying the URL that represents this activity.
   */
  public final native void setUrl(String url) /*-{
    this[$wnd.opensocial.Activity.Field.URL] = url;
  }-*/;

  /**
   *
   * @param userId The string ID of the user who this activity is for.
   */
  public final native void setUserId(String userId) /*-{
    this[$wnd.opensocial.Activity.Field.USER_ID] = userId;
  }-*/;
}
