#!/bin/sh
APPDIR=..;
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-mac.jar:../../../gwt-google-apis.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.google.gwt.gears.sample.gwtnote.GWTNote/GWTNote.html;
