#!/bin/sh
APPDIR=../..;
if [ "$GWT_HOME" == "" ]; then
	echo "The environment variable GWT_HOME is not defined, it should point to a valid GWT installation."
	exit
fi

java -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar:../../../../gwt-template.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.google.gwt.template.sample.template.HelloTemplate/HelloTemplate.html;
