#!/bin/sh
APPDIR=..;
java -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar:../../../gwt-google-apis.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.google.gwt.gears.sample.database.DatabaseDemo/DatabaseDemo.html;
